# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
    assignees:
      - "clouddrove-ci"
    reviewers:
      - "approvers"

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/complete" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/byte_match_statement_rules" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/geo_allowlist_statement_rules" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/geo_match_statement_rules" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/ip_set_reference_statement_rules" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/managed_rule _group_statement" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/rate_based_statement_rules" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/regex_match_statement_rules" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/size_constraint_statement_rules" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/sqli_match_statement_rules" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3

  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/examples/xss_match_statement" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "clouddrove-ci"
    # Add reviewer
    reviewers:
      - "approvers"
    # Allow up to 3 open pull requests for pip dependencies
    open-pull-requests-limit: 3
